'use strict';
const products=[{id:1,name:'Nova Keyboard',category:'Gear',price:1290000,stock:8,discount:15,tags:['Wireless','RGB'],description:'Bàn phím cơ 75%, kết nối ba thiết bị.',image:'⌨️'},{id:2,name:'Pulse Headphones',category:'Audio',price:890000,stock:3,discount:10,tags:['Bluetooth','ANC'],description:'Tai nghe nhẹ với chống ồn chủ động.',image:'🎧'},{id:3,name:'Orbit Desk Light',category:'Desk',price:490000,stock:0,discount:0,tags:['LED','USB-C'],description:'Đèn bàn đổi nhiệt độ màu theo thời gian.',image:'💡'},{id:4,name:'Flow Mouse',category:'Gear',price:650000,stock:12,discount:5,tags:['Silent','Ergonomic'],description:'Chuột không dây yên tĩnh cho ngày làm việc dài.',image:'🖱️'},{id:5,name:'Arc Stand',category:'Desk',price:420000,stock:6,discount:0,tags:['Aluminium'],description:'Giá đỡ laptop thoáng khí, điều chỉnh độ cao.',image:'💻'},{id:6,name:'Wave Speaker',category:'Audio',price:760000,stock:4,discount:12,tags:['Stereo','USB-C'],description:'Loa desktop nhỏ gọn với âm thanh cân bằng.',image:'🔊'}];
let cart=[];
const money=value=>value.toLocaleString('vi-VN')+'đ';
const finalPrice=product=>Math.round(product.price*(1-product.discount/100));
function createText(tag,text,className){const element=document.createElement(tag);element.textContent=text;if(className)element.className=className;return element;}
function stockInfo(product){if(product.stock===0)return{label:'Hết hàng',className:'out'};if(product.stock<5)return{label:'Chỉ còn '+product.stock,className:'low'};return{label:'Còn hàng',className:''};}
function createProductCard(product){const card=document.createElement('article');card.className='product-card';if(product.discount){const sale=createText('span','-'+product.discount+'%','sale');card.appendChild(sale);}const image=createText('div',product.image,'product-image');image.setAttribute('role','img');image.setAttribute('aria-label','Minh họa '+product.name);const category=createText('p',product.category,'category');const title=createText('h3',product.name);const description=createText('p',product.description,'description');const tags=document.createElement('div');tags.className='tags';product.tags.forEach(tag=>tags.appendChild(createText('span',tag)));const stock=stockInfo(product);const stockEl=createText('span',stock.label,'stock '+stock.className);const footer=document.createElement('div');footer.className='product-footer';const price=createText('strong',money(finalPrice(product)));const add=document.createElement('button');add.type='button';add.textContent=product.stock?'Thêm vào giỏ':'Hết hàng';add.disabled=!product.stock;add.addEventListener('click',()=>addToCart(product.id));const info=document.createElement('div');info.append(price,stockEl);footer.append(info,add);card.append(image,category,title,description,tags,footer);return card;}
function getVisibleProducts(){const query=document.querySelector('#search').value.trim().toLowerCase();const category=document.querySelector('#category').value;const sort=document.querySelector('#sort').value;let result=products.filter(product=>[product.name,product.description,...product.tags].join(' ').toLowerCase().includes(query)&&(category==='all'||product.category===category));if(sort==='price-asc')result=[...result].sort((a,b)=>finalPrice(a)-finalPrice(b));if(sort==='price-desc')result=[...result].sort((a,b)=>finalPrice(b)-finalPrice(a));return result;}
function renderProducts(){const visible=getVisibleProducts();const root=document.querySelector('#product-grid');root.textContent='';visible.forEach(product=>root.appendChild(createProductCard(product)));if(!visible.length)root.appendChild(createText('p','Không tìm thấy sản phẩm phù hợp.'));document.querySelector('#result-count').textContent=visible.length+' sản phẩm';}
function addToCart(productId){const product=products.find(item=>item.id===productId);const existing=cart.find(item=>item.productId===productId);if(existing)existing.quantity=Math.min(existing.quantity+1,product.stock);else cart=[...cart,{productId:productId,quantity:1}];renderCart();openCart();}
function updateQuantity(productId,change){const product=products.find(item=>item.id===productId);cart=cart.map(item=>item.productId===productId?{...item,quantity:Math.max(0,Math.min(product.stock,item.quantity+change))}:item).filter(item=>item.quantity>0);renderCart();}
function removeFromCart(productId){cart=cart.filter(item=>item.productId!==productId);renderCart();}
function cartTotal(){return cart.reduce((sum,item)=>{const product=products.find(entry=>entry.id===item.productId);return sum+finalPrice(product)*item.quantity;},0);}
function renderCart(){const root=document.querySelector('#cart-items');root.textContent='';const count=cart.reduce((sum,item)=>sum+item.quantity,0);document.querySelector('#cart-count').textContent=count;if(!cart.length)root.appendChild(createText('p','Giỏ hàng đang trống.'));cart.forEach(item=>{const product=products.find(entry=>entry.id===item.productId);const row=document.createElement('article');row.className='cart-item';const info=document.createElement('div');info.append(createText('strong',product.name),createText('p',money(finalPrice(product))+' × '+item.quantity));const controls=document.createElement('div');controls.className='quantity';const minus=createText('button','−');minus.type='button';minus.setAttribute('aria-label','Giảm '+product.name);minus.addEventListener('click',()=>updateQuantity(product.id,-1));const quantity=createText('span',String(item.quantity));const plus=createText('button','+');plus.type='button';plus.setAttribute('aria-label','Tăng '+product.name);plus.addEventListener('click',()=>updateQuantity(product.id,1));const remove=createText('button','Xóa','remove');remove.type='button';remove.addEventListener('click',()=>removeFromCart(product.id));controls.append(minus,quantity,plus,remove);row.append(info,controls);root.appendChild(row);});document.querySelector('#cart-total').textContent=money(cartTotal());}
const drawer=document.querySelector('#cart-drawer');const overlay=document.querySelector('#overlay');const cartButton=document.querySelector('#cart-button');function openCart(){drawer.hidden=false;overlay.hidden=false;document.body.classList.add('cart-open');cartButton.setAttribute('aria-expanded','true');document.querySelector('#cart-close').focus();}function closeCart(){drawer.hidden=true;overlay.hidden=true;document.body.classList.remove('cart-open');cartButton.setAttribute('aria-expanded','false');cartButton.focus();}cartButton.addEventListener('click',openCart);document.querySelector('#cart-close').addEventListener('click',closeCart);overlay.addEventListener('click',closeCart);document.addEventListener('keydown',event=>{if(event.key==='Escape'&&!drawer.hidden)closeCart();});
const themeButton=document.querySelector('#theme-toggle');themeButton.addEventListener('click',()=>{const light=document.body.classList.toggle('light');themeButton.setAttribute('aria-pressed',String(light));themeButton.setAttribute('aria-label',light?'Bật giao diện tối':'Bật giao diện sáng');});
document.querySelector('#search').addEventListener('input',renderProducts);document.querySelector('#category').addEventListener('change',renderProducts);document.querySelector('#sort').addEventListener('change',renderProducts);document.querySelector('#newsletter-form').addEventListener('submit',event=>{event.preventDefault();document.querySelector('#form-status').textContent='Đăng ký thành công! Hẹn gặp bạn trong bản tin tiếp theo.';event.target.reset();});document.querySelector('#checkout').addEventListener('click',()=>{document.querySelector('#cart-status').textContent=cart.length?'Demo: đơn hàng đã sẵn sàng để checkout.':'Hãy thêm ít nhất một sản phẩm.';});
const categorySelect=document.querySelector('#category');[...new Set(products.map(product=>product.category))].forEach(category=>{const option=createText('option',category);option.value=category;categorySelect.appendChild(option);});renderProducts();renderCart();
